// Single source of truth for car inventory.
// Edit, add, or remove entries here — index.html and car.html both read from this file.
// Prices in SGD, mileage in km, COE expiry as shown on the vehicle's logbook.
const CARS = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2021,
    price: 118800,
    mileage: 51000,
    plateNumber: "SGX 1234 A",
    coeExpiry: "Mar 2031",
    color: "Midnight Blue",
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "Sedan",
    description:
      "A reliable, fuel-efficient sedan in excellent condition. Full service history, single previous owner, and recently replaced tires. Great daily driver with a smooth ride and modern infotainment system.",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/65/2021_Toyota_Camry_TRD_V6.jpg",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/File:2021_Toyota_Camry_TRD_V6.jpg",
    featured: true,
  },
  {
    id: 2,
    make: "Honda",
    model: "CR-V",
    year: 2020,
    price: 108500,
    mileage: 66000,
    plateNumber: "SJT 5678 B",
    coeExpiry: "Jun 2030",
    color: "Pearl White",
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "SUV",
    description:
      "Spacious family SUV with plenty of cargo room and all-wheel drive. Well maintained with regular servicing at the dealership. Includes roof rails and a rear-view camera.",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Honda_CR-V.JPG",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Honda_CR-V.JPG",
    featured: true,
  },
  {
    id: 3,
    make: "Toyota",
    model: "Alphard",
    year: 2019,
    price: 168000,
    mileage: 88000,
    plateNumber: "SLB 9012 C",
    coeExpiry: "Nov 2029",
    color: "Pearl White",
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "MPV",
    description:
      "The quintessential Singapore family MPV — spacious captain seats, sliding doors, and a smooth ride for the whole family. Well maintained with complete servicing records. Popular choice for weekend Malaysia trips.",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/57/2023_Toyota_Alphard_Hybrid_%28AH40%29_1.jpg",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/File:2023_Toyota_Alphard_Hybrid_(AH40)_1.jpg",
    featured: false,
  },
  {
    id: 4,
    make: "Volkswagen",
    model: "Golf",
    year: 2022,
    price: 98800,
    mileage: 29000,
    plateNumber: "SMK 3456 D",
    coeExpiry: "Feb 2032",
    color: "Graphite Gray",
    transmission: "Manual",
    fuel: "Petrol",
    bodyType: "Hatchback",
    description:
      "Compact, agile hatchback with low mileage and a manual gearbox for driving enthusiasts. Still under manufacturer warranty. Clean interior, no smoking history.",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Volkswagen_Golf_VIII_2.0_TSI_%282022%29_%2854716801451%29.jpg",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Volkswagen_Golf_VIII_2.0_TSI_(2022)_(54716801451).jpg",
    featured: false,
  },
  {
    id: 5,
    make: "BMW",
    model: "4 Series",
    year: 2020,
    price: 158000,
    mileage: 45000,
    plateNumber: "SHA 7890 E",
    coeExpiry: "Aug 2030",
    color: "Alpine White",
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "Coupe",
    description:
      "Sporty and elegant coupe with premium leather interior and upgraded sound system. Turns heads wherever it goes. Recently detailed, drives like new.",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/31/BMW_4Series_Coupe_01.JPG",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/File:BMW_4Series_Coupe_01.JPG",
    featured: true,
  },
  {
    id: 6,
    make: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 179000,
    mileage: 15000,
    plateNumber: "SEV 2468 F",
    coeExpiry: "May 2033",
    color: "Deep Blue Metallic",
    transmission: "Automatic",
    fuel: "Electric",
    bodyType: "EV Sedan",
    description:
      "Nearly new electric sedan with Autopilot, long range battery, and minimal mileage. Cheap to charge overnight and exempt from ERP surcharges. A fantastic entry into EV ownership in Singapore.",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Tesla_Model_3_Front_View.jpg",
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Tesla_Model_3_Front_View.jpg",
    featured: false,
  },
];
